### PR TITLE
Support for OPENAI_ORGANIZATION Header in OpenAI Client

### PR DESCRIPTION
**Pull request by samuelcardoso**
### What's being changed:

This pull request introduces the ability to accept an additional header X-Openai-Organization. If this header is present in the request, we will now add an additional header OPENAI_ORGANIZATION to OpenAI.

This update will help streamline our API usage and improve our compatibility with OpenAI API's recent changes.

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by kirby-jobber** [comment]
Some places that might also need to be updated to reflect organization ID support:

- Doc pages for relevant [text2vec](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-openai), [qna](https://weaviate.io/developers/weaviate/modules/reader-generator-modules/qna-openai), and [generative](https://weaviate.io/developers/weaviate/modules/reader-generator-modules/generative-openai) modules.
- [docker-compose docs](https://weaviate.io/developers/weaviate/installation/docker-compose), including the configurator logic. 
- Possibly the Weaviate client libraries and client library docs?

**Comment by antas-marcin** [comment]
@samuelcardoso in order to be able to merge your PR, you need to agree to our CLA. Can you make a comment saying `I agree to CLA` so that I could merge it?

**Comment by antas-marcin** [comment]
I will then polish your solution and include it in our next `v1.21.1` patch release

**Comment by antas-marcin** [comment]
I'm closing this PR, it has been implemented in PR #3439

**Pull request closed without merging**
