### PR TITLE
quoted ports in docker-compose

### PR DESCRIPTION
**Pull request by Deegiimurun**
### What's being changed:

- Quoted ports on docker compose

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by dirkkul** [comment]
Hi @Deegiimurun,
why would this be better than unquoted ports?

**Comment by dirkkul** [comment]
ah thanks, I did not know that.
Would you also change the ports in the docker-compose-test file?

**Comment by Deegiimurun** [comment]
It is already quoted.

**Comment by dirkkul** [comment]
thanks!

**Pull request merged**
