### PR TITLE
added a guard in KnnSearchByVector function and test coverage

### PR DESCRIPTION
**Pull request by amityahav**
### What's being changed:
#3263 
Added a guard in KnnSearchByVector function and a test in index_test.go as well
its unlikely to panic because of that in production because this function is not called directly and the wrapper functions already use the default k value in case, its still good that there is an extra guard

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [X] All new code is covered by tests where it is reasonable.
- [X] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by amityahav** [comment]
I agree with the cla

**Comment by dirkkul** [comment]
Hi @amityahav 

could you rebase your PR on the latest master? Them we can merge it

**Comment by amityahav** [comment]
sure will do later, thanks!

**Comment by dirkkul** [comment]
@amityahav there are now 300+ commits in this PR - could you have a look what happened there?

**Comment by dirkkul** [comment]
might be the easiest, just link it here then I'll be notified

**Comment by amityahav** [comment]
#3512

**Comment by parkerduckworth** [comment]
Closing since this was handled in #3512

**Pull request closed without merging**
