### PR TITLE
adapters/grpc: remove redundant nil check in `extractPrimitiveProperties`

### PR DESCRIPTION
**Pull request by Juneezee**
### What's being changed:

From the Go specification [^1]:

> "1. ... For a nil slice, the number of iterations is 0."

Therefore, an additional nil check for around the loop is unnecessary.

[^1]: https://go.dev/ref/spec#For_range

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [x] Chaos pipeline run or not necessary. Link to pipeline:
- [x] All new code is covered by tests where it is reasonable.
- [x] Performance tests have been run or not necessary.

### CODE REVIEW

**Review by Juneezee — COMMENTED** [review]
Tip: hide the whitespace changes to make the diff easier to read

image

**Comment by Juneezee** [comment]
> To avoid any confusion in the future about your contribution to Weaviate, we work with a [Contributor License Agreement](https://weaviate.io/service/contributor-license-agreement). If you agree, you can simply add a comment to this PR that you agree with the CLA so that we can merge.beep boop - the Weaviate bot 👋🤖PS:Are you already a member of the [Weaviate Slack channel?](https://weaviate.io/slack)

@weaviate-git-bot I agree with the CLA.

**Comment by dirkkul** [comment]
Hi @Juneezee thank you for your contribution! Could you change the target to stable/1.23? Then I'll merge :)

**Comment by dirkkul** [comment]
Hi @Juneezee - you added all the master commits - might be easier to just make a new branch/PR with your commit on top. Feel free to ping me then

**Comment by Juneezee** [comment]
@dirkkul Please take a look again. I have cherry-picked the commit to `stable/v1.23`.

**Review by dirkkul — APPROVED** [review]
thank you!

**Pull request merged**
