### PR TITLE
Fix timeout when trying to insert object while Azure OpenAI is out of tokens

### PR DESCRIPTION
**Pull request by andrewisplinghoff**
### What's being changed:
Best first merge https://github.com/weaviate/weaviate/pull/5657 as this builds on top.

This fixes what happens when `x-ratelimit-remaining-tokens` is too low for inserting the next object. In the old code, this lead to the whole batch import to fail with a timeout, because Azure OpenAI does not provide a value for the `x-ratelimit-reset-tokens` header value at least for successful vectorization requests. Not having a value for that header value leads to `rateLimit.ResetTokens ` to be set to `time.Now()` here: https://github.com/weaviate/weaviate/blob/aba0017951205e2b078d364299d1a9e61776e84a/modules/text2vec-openai/ent/vectorization_result.go#L51
Therefore when checking `rateLimit.ResetTokens` later (https://github.com/weaviate/weaviate/blob/aba0017951205e2b078d364299d1a9e61776e84a/usecases/modulecomponents/batch/batch.go#L294), the `ResetTokens` time is in the past and not in the future, leading to a skip over that if clause and repeated calls to `makeRequest()` with an empty `texts` array, which is invalid and results in an error response from Azure OpenAI.

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [x] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by dirkkul** [comment]
Thanks for your investigation!

I would prefer that we set the refresh time in `GetVectorizerRateLimit` of the openAI module instead of adapting the batch background goroutine. This is already done for some other vectorizers, check here for example: https://github.com/weaviate/weaviate/blob/a1598532c5e59c3da41174f70ed6b2416f6951cb/modules/text2vec-voyageai/clients/voyageai.go#L193

**Comment by andrewisplinghoff** [comment]
> Thanks for your investigation!
> 
> I would prefer that we set the refresh time in `GetVectorizerRateLimit` of the openAI module instead of adapting the batch background goroutine. This is already done for some other vectorizers, check here for example:
> 
> https://github.com/weaviate/weaviate/blob/a1598532c5e59c3da41174f70ed6b2416f6951cb/modules/text2vec-voyageai/clients/voyageai.go#L193

OK thanks for the feedback, I can change the code accordingly.

I still think there needs to be some safety mechanism within the generic batch class, as also other vectorizers might fail to set `rateLimit.ResetTokens` to a time in the future and by doing so leading to a loop of calls to the vectorizer with an empty `texts` array.
https://github.com/weaviate/weaviate/blob/aba0017951205e2b078d364299d1a9e61776e84a/usecases/modulecomponents/batch/batch.go#L294
Do you have an idea what a solution for that case might look like? Would be better to abort the batch process immediately when this is detected instead of looping over and over.

**Comment by dirkkul** [comment]
>  Do you have an idea what a solution for that case might look like? Would be better to abort the batch process immediately when this is detected instead of looping over and over.

agreed. I think in this case aborting the whole batch would make the most sense

**Comment by andrewisplinghoff** [comment]
@dirkkul I adjusted the PR to not change the generic batch vectorizer but instead only fix this by setting `rateLimit.ResetTokens` to a more appropriate value just for the (Azure) OpenAI vectorizer.

I tried to find a way to implement what we discussed to fail the whole batch in the case discussed earlier, but did not find an appropriately easy way to do so. Adding errors to all remaining objects in `job.errs`, marking the job waitGroup to be done, decreasing current batches would be a whole lot of duplicated code what I wouldn't think is a good solution. Not sure if there maybe is some way to cancel the context or so?

Anyway, this PR could be merged as is and if there is a straightforward way of fixing this problem from occurring again for other vectorizers by making improvements to the `sendBatch()` method, this could be done as a next step in another PR.

**Comment by dirkkul** [comment]
>@dirkkul I adjusted the PR to not change the generic batch vectorizer but instead only fix this by setting rateLimit.ResetTokens to a more appropriate value just for the (Azure) OpenAI vectorizer.

Thanks!

I am unsure if there is a better way of solving this, but I think your solution is better than what was there before, so we can go with it.

> I tried to find a way to implement what we discussed to fail the whole batch in the case discussed earlier, but did not find an appropriately easy way to do so. Adding errors to all remaining objects in job.errs, marking the job waitGroup to be done, decreasing current batches would be a whole lot of duplicated code what I wouldn't think is a good solution. Not sure if there maybe is some way to cancel the context or so?

This should be all you need to do:
```
				for j := origIndex[0]; j < len(job.texts); j++ {
					if !job.skipObject[j] {
						job.errs[j] = errors.New("request rate limit exceeded and will not refresh in time")
					}
				}
				break
```
you might even factor out setting the errors to reuse that code

**Review by dirkkul — APPROVED** [review]

**Comment by andrewisplinghoff** [comment]
> I am unsure if there is a better way of solving this, but I think your solution is better than what was there before, so we can go with it.

Yes, it is certainly not optimal, especially due to the high dummy limit there will only be very small times used for sleeping in `sendBatch()`. But at least with the new code the user is now able to handle token limit related problems on the client side as the errors now correctly get returned to the client.

**Pull request merged**
