### PR TITLE
new module: generative-transformers

### PR DESCRIPTION
**Pull request by AlMaenkov**
### What's being changed:

This PR adds 1 new module: generative-transformers this module may be useful for creating generative search using own models and models from hugging face by using simple rest API on /prompt endpoint

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by antas-marcin** [comment]
@AlMaenkov Thank you for your contribution. I have a question about this module, to which service does this module suppose to connect? huggingface? and which model / models does it support?

**Comment by AlMaenkov** [comment]
> @AlMaenkov Thank you for your contribution. I have a question about this module, to which service does this module suppose to connect? huggingface? and which model / models does it support?

Hello! I was thinking about self-hosted rest service which could work as this one https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules/text2vec-transformers and i thought about adding support for text generation models from huggingface. If it necessary i also can try add module for integration with huggingface and for example call it generative-huggingface.

For example if i want to test https://huggingface.co/openlm-research/open_llama_13b as a base model for generative search i can't do it now, but this module gives me this opportunity

**Comment by AlMaenkov** [comment]
I agree with the CLA

**Comment by AlMaenkov** [comment]
@antas-marcin I tried to run `./tools/gen-code-from-swagger.sh` script so that the stage in CI passes, but on my side it's only remove information about weaviate copyright from source files. I think I do something wrong, can you help me?

**Comment by antas-marcin** [comment]
@AlMaenkov can you rebase your PR with our current `master` changes?

**Pull request closed without merging**
