### PR TITLE
Lock-free BM25Searcher::wand() implementation

### PR DESCRIPTION
**Pull request by arturmelanchyk**
### What's being changed:
Removing `sync.Mutex` lock and avoiding unneeded memory allocations in BM25Searcher::wand().
Existing implementation of the `for` loop implies (worst case):
- `Lock()`/`Unlock()` invocations = `len(Tokenizations) x len(queryTerms)` times
- slice memory re-allocation with `append`  = `len(Tokenizations) x len(queryTerms)` times

Suggested implementation:
- no locks
- memory allocations = `len(Tokenizations)` times
- `one` allocation for the aggregated final result

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by arturmelanchyk** [comment]
I agree with the Contributor License Agreement

**Comment by arturmelanchyk** [comment]
Hi @etiennedi could you please look into this?

**Comment by arturmelanchyk** [comment]
Hi guys, any update on this PR?

**Comment by arturmelanchyk** [comment]
Just a kind reminder @etiennedi

**Comment by pommedeterresautee** [comment]
Did you noticed perf improvement on bm25 search for large index?

**Comment by moogacs** [comment]
thanks for contributing @arturmelanchyk , sorry for late response, could please resolve conflicts and pull latest changes ?

**Pull request closed without merging**
