### PR TITLE
update(text2vec-cohere): Updated embed model names

### PR DESCRIPTION
**Pull request by aaliboyev**
### What's being changed:
In respect to cohere embed model names change updated the available models for text2vec-cohere module
references: [blogpost: Model Names Are Changing!](https://docs.cohere.com/changelog/model-names-are-changing) and: [api reference here](https://docs.cohere.com/reference/embed)
### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by trengrj** [comment]
Thanks @aaliboyev rather than deleting the old model names we should keep them for backwards compatibility.

**Comment by antas-marcin** [comment]
@aaliboyev can you also rebase your PR with `stable/v1.19` branch? and change the base of your PR from `master` to `stable/v1.19`? I would like to have this change released with our patch release (which will be released sooner then `v1.20`)

**Comment by antas-marcin** [comment]
@aaliboyev we had to move quickly with this change, so I have implemented all of the Cohere Model changes in this [PR](https://github.com/weaviate/weaviate/pull/3117) so that we will be able to release this change today.

I'm closing your PR.

Thank you for pointing this change to us!

**Comment by aaliboyev** [comment]
Sorry for missing messages guys. Happy to help and no problems with closing this pr. Thank you

**Pull request closed without merging**
