### PR TITLE
Add Another Vector Search ANN Option Based On Hardware Acceleration

### PR DESCRIPTION
**Pull request by sourcesync**
### What's being changed:

We are adding another ANN option (called Gemini) to Weaviate based on our custom hardware accelerator technology called the Associative Processor Unit (APU):
* We've added an additional vector search index (stub) under adapters/repos/db/index.
* We've added an additional vector search entity under entities/vectorIndex.
* We've added a new Golang module which implements the index, which itself is mostly a Golang wrapper of our Fast Vector Search REST web service.

There is a more detailed "gsi/README.md" about our approach, the system architecture, configuration for both server and client, and our integration roadmap

### Review checklist

We request (high-level) feedback about the following:
- [ ] Review our current system architecture.
- [ ] Review our Golang integration strategy within the main Weaviate code base and the external module.
- [ ] Review our Weaviate container configuration steps.
- [ ] Review how a Weaviate application client specifies this new index type.
- [ ] Run the "Quick Start" instructions ( we can give you access to a system with our custom hardware installed. )
- [ ] Anything else we may be missing in this PR...

### CODE REVIEW

**Comment by sourcesync** [comment]
> To avoid any confusion in the future about your contribution to Weaviate, we work with a [Contributor License Agreement](https://www.semi.technology/playbooks/misc/contributor-license-agreement.html). If you agree, you can simply add a comment to this PR that you agree with the CLA so that we can merge.beep boop - the SeMI bot 👋🤖PS:Are you already a member of the [Weaviate Slack channel?](https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw)

We agree with the CLA (Contributor License Agreement).  Yes, we are members of the Weaviate Slack Channel as well!  Thanks!

**Comment by sourcesync** [comment]
Thank you for the notification.  Yes, please keep this PR open.  We do hope you have time to give us feedback on this PR when you can, thanks!

**Comment by sourcesync** [comment]
Thank you for the notification. Yes, please keep this PR open. We do hope you have time to give us feedback on this PR when you can, thanks!

**Comment by etiennedi** [comment]
Thank you for the contribution. After discussing internally, we have decided to close this PR. At 30,000+ lines and several merge conflicts, a review from our side is not feasible unfortunately.

**Pull request closed without merging**
