### PR TITLE
fix extractAdditionalPropsFromMetadata not using the linkedClass

### PR DESCRIPTION
**Pull request by paul7Junior**
### What's being changed:

This pull request is linked to the issue:  https://github.com/weaviate/weaviate/issues/6279

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by dirkkul** [comment]
Hey!

Could you add a test? :) You can use your example code and add a test here: test/acceptance_with_python/test_named_vectors.py

Also, could you target an older stable branch? I think that code hasn't change in a while so targeting stable/v1.25 or stable/v1.26 should be fine. This way it can be in the next stable release.

(internal note, user agreed to CLA here: https://github.com/weaviate/weaviate-python-client/pull/1399#issuecomment-2468301837)

**Comment by paul7Junior** [comment]
Hey Dirk, 

Sure, I'll look at that and reach out if i have any issue.

**Comment by dirkkul** [comment]
Hey @paul7Junior , I just ran into this bug for a different problem that I needed to fix asap. I took your commit, added a test and changed the target to stable/v1.26 here: https://github.com/weaviate/weaviate/pull/6347

**Comment by paul7Junior** [comment]
Hey @dirkkul 

sorry about that. but thanks so much for the fix and the update.

**Comment by dirkkul** [comment]
no worries! Thanks for providing such a great issue and the fix! Was very quick to finish this :)

**Pull request closed without merging**
