### PR TITLE
Added code numeric to error object

### PR DESCRIPTION
**Pull request by tamoghnokandar**
### What's being changed:
Fixes [#2588](https://github.com/weaviate/weaviate/issues/2588)
Added a <code>code</code> numeric to the <code>error</code> object. 

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by tamoghnokandar** [comment]
@kcm Can you review this PR?

**Comment by kcm** [comment]
Hi @tamoghnokandar! Thanks for the PR. Can you also address at least the `429` error mentioned in the original issue, as well as any others you may find?

**Comment by etiennedi** [comment]
Converted to draft, as this does yet seem to solve the issue described in #2588 (see @kcm 's comment)

**Comment by dirkkul** [comment]
I will close this as there hasn't been any activity for 3 weeks, please open a new PR if you implemented the required changes, thanks!

**Pull request closed without merging**
