### PR TITLE
fix slice init length

### PR DESCRIPTION
**Pull request by hongmengning**
### What's being changed:

Fix slice initialization error

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by hongmengning** [comment]
> To avoid any confusion in the future about your contribution to Weaviate, we work with a [Contributor License Agreement](https://weaviate.io/service/contributor-license-agreement). If you agree, you can simply add a comment to this PR that you agree with the CLA so that we can merge.beep boop - the Weaviate bot 👋🤖PS:Are you already a member of the [Weaviate Slack channel?](https://weaviate.io/slack)

I agree the CLA.

**Comment by hongmengning** [comment]
> hey @hongmengning - thank you for your contribution!
> 
> I think this fix is correct - did it have any effect and if yes, would it be possible to add a test for it?



> hey @hongmengning - thank you for your contribution!
> 
> I think this fix is correct - did it have any effect and if yes, would it be possible to add a test for it?

Thanks. The testcase had added.

**Comment by dirkkul** [comment]
Thank you! 

Could you fix the linter warnings?
https://github.com/weaviate/weaviate/actions/runs/10860259949?pr=5774

Also if possible, would be great if your PR could target a stable branch (stable/v1.25 if possible), then the fix would be in the next release. Might be easier to just branch off that stable branch and cherry pick your commit.

**Comment by dirkkul** [comment]
Closing as the test does not compile and not really test the new code

**Pull request closed without merging**
