### PR TITLE
Feature/2481 add support for wildcards for include exclude backups

### PR DESCRIPTION
**Pull request by iangregson**
### What's being changed:

Closes [#2481 :: add support for wildcards in class lists](https://github.com/weaviate/weaviate/issues/2481)

* Add a helper function to detect if the class list contains wildcards.
* Use that helper in each Include / Exclude function to branch into generating predicate functions that do string comparison (prefix/suffix) instead of set membership.
* Add new test cases to Include / Exclude tests that cover the use of wildcard in the inclusion / exclusion lists.

### Review checklist

- [x] Documentation has been updated, if necessary. Link to changed documentation: https://github.com/weaviate/weaviate-io/pull/821
- [ ] Chaos pipeline run or not necessary. Link to pipeline: noob can haz Chaos Pipeline?
- [x] All new code is covered by tests where it is reasonable.
- [x] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by iangregson** [comment]
I agree ✅

**Comment by dirkkul** [comment]
Thanks @iangregson, I quickly fixed the linter error in a follow up PR. I kept your commits so your contribution is recognized :)

**Comment by iangregson** [comment]
Awesome. Thanks @dirkkul !

**Comment by dirkkul** [comment]
Uhh I'm sorry, I did that for your PR to the python repo, not to this one

**Comment by dudanogueira** [comment]
hi @iangregson ! Sorry that this PR got closed and not merged. 

We added a [bounty to it at the issue](https://github.com/weaviate/weaviate/issues/2481). Let us know if you are interested.

And thanks for your contribution!

**Pull request closed without merging**
