### PR TITLE
fix: trim api res instead of remove all newlines

### PR DESCRIPTION
**Pull request by felizalde**
### What's being changed:

This PR is to fix: #2610

### CODE REVIEW

**Comment by etiennedi** [comment]
Hi @felizalde,

Thank you for your contribution!

- @byronvoorbach could you please review?
- @bobvanluijt it seems that the CLA bot no longer works. This is a potential first-time contribution, but the bot did not ask to agree with the CLA
- @felizalde with `master` as the merge target this would potentially land in `v1.18`. That's fine, but you could also rebase this onto `stable/v1.17` and make the merge target `stable/v1.17`, then we could release it earlier as a `v1.17.x` patch.

**Review by byronvoorbach — COMMENTED** [review]
LGTM!

**Comment by etiennedi** [comment]
Thanks! It seems our CLA bot is currently broken, so let me post the [CLA](https://weaviate.io/service/contributor-license-agreement) manually. 

If you agree, let me know, and then we can merge.

**Comment by felizalde** [comment]
I agree. Thanks.

**Pull request merged**
