### PR TITLE
Feat: Filtering poor results in Hybrid search (`AcceptanceThreshold`)

### PR DESCRIPTION
**Pull request by dresslife-shbh**
Filtered vector and keyword search results according to threshold parameters in hybrid search.

/claim #4315

Changes

1.New param AcceptanceThreshold is added to Hybrid search function , which will help in filtering out very poor results from vector and keyword search, before combining the results.

2. Added the filtering

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [x] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by donomii** [comment]
HI,
could you please merge the current main into your patch?  We apologise, but they are now out of sync

**Comment by dresslife-shbh** [comment]
@donomii PR is rebased

**Comment by donomii** [comment]
Thanks for your contribution, it's compiling and running now.  Could I ask a question?  In you code, you have added `AcceptanceThreshold`, but I don't see where that value is set.  Could you describe how the user will set this value?

**Comment by dirkkul** [comment]
I had a look and don't think this solves the issue:
- No way to set the cutoff from the outside/not added to API
- No tests, that the functionality works
- Vector cutoff is only used in the nearVector Subsearch, not in the other (sub-) searches
- Results that are removed from the vector search, are not removed from the BM25 search and will still be present in the final results
- AcceptannceThreshold.MinHybridScore is used as a cutoff of BM25 scores, which is very confusing

Will close the PR

**Pull request closed without merging**
