### PR TITLE
husky to automate pre-commit

### PR DESCRIPTION
**Pull request by Deegiimurun**
### What's being changed:

- deleted .pre-commit-config.yaml, since it was requiring user to manually install gofumpt, pre-commit.
- added husky to automate installing gofumpt, formatting, running swagger before every commit.

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [x] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by dirkkul** [comment]
hi, could you provide a bit more info about husky? Never heard of that, thanks!

**Comment by Deegiimurun** [comment]
Well it has same purpose as the pre-commit which project is currently using. Husky is a go library that needs to be downloaded as go package. After download, purpose is same, using shell file to run some command beffore commit. I think downside of pre-commit is that developer manually has to install it on system (also gofumpt which pre-commit is using). Since after cloning project developer needs to install go packages anyway, so husky is installed automatically.

**Comment by Deegiimurun** [comment]
Well, it has the same purpose as the pre-commit that the project is currently using. Husky is a go library that needs to be downloaded as go package. After download, the purpose is the same, using the shell file to run some commands before commit. I think downside of pre-commit is that developer manually has to install it on system (also gofumpt which pre-commit is using). Since after cloning a project developer needs to install go packages anyway, so husky is installed automatically. Thus no need to manually install things to run commands pre-commit.

**Comment by Deegiimurun** [comment]
Well, it has the same purpose as the pre-commit that the project is currently using. Husky is a go library that needs to be downloaded as go package. After download, the purpose is the same, using the shell file to run some commands before commit. I think downside of pre-commit is that developer manually has to install it on system (also gofumpt which pre-commit is using). Since after cloning a project developer needs to install go packages anyway, so husky is installed automatically. Thus no need to manually install things to run commands pre-commit. 

Also I think the current process is error-prone (since the developer has to run swagger manually after every commit).

**Comment by dirkkul** [comment]
I think I'd rather keep pre-commit, but please add swagger :)

Nothing against husky, but I know pre-commit and we're using it in many repositories and I currently do not have the time to look into another library.

**Comment by Deegiimurun** [comment]
Yeah sure, closing this one.

**Pull request closed without merging**
