### PR TITLE
Nit: Fix function comments that don't start w func name

### PR DESCRIPTION
**Pull request by DataDavD**
Refactor function comments for go doc.

Note: I got bored and did this since it kinda annoyed me when working on another PR, so feel free to ignore and close this PR if y'a want.

### CODE REVIEW

**Comment by reyreaud-l** [comment]
Thanks a lot for these changes, it's something we're looking at getting better. Not all the comment are perfect but they'll get picked up by GoDoc and that's already a good first step. Thanks!

**Comment by reyreaud-l** [comment]
One thing before we can merge your work (We should have a bot asking for this but it didn't trigger ?) Do you accept our contribution agreement & guidelines ? See here https://github.com/weaviate/weaviate/blob/main/CONTRIBUTING.md#agreements.

Please explicitly state in this PR that you agree with it and we can merge your work :)

**Comment by antas-marcin** [comment]
@DataDavD Simply stating in comment "I agree with CLA" will enable us to merge your PR

**Comment by DataDavD** [comment]
Hey friends, sorry for the response. Happy to help in any form.

I agree with CLA

**Comment by DataDavD** [comment]
hey friends, sorry for the bump, just wondering if y'all saw the PR should be good now.

cheers

**Comment by DataDavD** [comment]
hey sorry, just bumping this.

**Comment by DataDavD** [comment]
hey @reyreaud-l @antas-marcin sorry to bother you two, but I was just curious if you saw that I had agreed to the CLA so that the PR passes the CLA gate

**Comment by DataDavD** [comment]
hey @reyreaud-l @antas-marcin, this has been approved for awhile, but hasn't been merged. Is there anything else I need to do? Or should I close it?

cheers

**Comment by moogacs** [comment]
👋🏼  Hey @DataDavD , thanks for opening this PR. i know it has been a while. could you please rebase the PR and resolve conflict in order to get it merged 

also if you can update the PR title to something like `chore(go-doc):  update doc to match the func name`

**Comment by DataDavD** [comment]
Thanks @moogacs ill take a look Monday evening

**Comment by DataDavD** [comment]
hey @moogacs just FYI. I wasn't able to get to it so far this weekend most likely won't until this weekend. sorry getting bogged down by a lot of work/life stuff. I'll keep y'a posted once it's reviewable again.

thank you.

**Comment by moogacs** [comment]
No worries at all, that's totally understandable. thanks again @DataDavD for your effort 🙏

**Comment by moogacs** [comment]
hey @DataDavD  i am gonna close this PR for now, feel free to reopen again once you resolve conflicts , thanks again for your contribution 🙏🏼

**Comment by DataDavD** [comment]
good call @moogacs . I'll just resubmit once I fix the conflicts. cheers

**Pull request closed without merging**
