### PR TITLE
Shell related refactors

### PR DESCRIPTION
**Pull request by Deegiimurun**
### What's being changed:

- Refactored few shell files (double quotes, typo etc)
- Deleted run_test_server.sh since it was not working also run_dev_server.sh is provided.

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by Deegiimurun** [comment]
Do not merge this one yet. Started working on #2633

**Comment by Deegiimurun** [comment]
Hi @etiennedi,

How could you review this commit?

**Comment by Deegiimurun** [comment]
Hi @etiennedi, could you review?

**Comment by Deegiimurun** [comment]
Hi @dirkkul, could you review? Need second opinion before finishing up.

**Comment by dirkkul** [comment]
merged the other one!

**Pull request closed without merging**
