### PR TITLE
feat: use mmap-go for windows support

### PR DESCRIPTION
**Pull request by ahmedalhulaibi**
### What's being changed:
- Adding support for windows to address https://github.com/weaviate/weaviate/issues/2955
- Added dependency on https://github.com/edsrzf/mmap-go to enable cross-platform mmap
- Updated unit tests so that they can run on windows
  - Mainly ensuring underlying files are closed before Go's `Testing.TempDir()` is cleaned up (which otherwise results in errors/panics in tests).
  - Updated some of the `connection refused` tests to support windows error messages

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by ahmedalhulaibi** [comment]
@weaviate-git-bot I agree to the CLA

**Comment by dirkkul** [comment]
HI @ahmedalhulaibi 

thank you for your contribution!

We are currently [discusing replacing mmap](https://github.com/weaviate/weaviate/issues/3091) and would put this PR on hold until we decided what to do with it.

**Comment by dirkkul** [comment]
Hi @ahmedalhulaibi 

we decided to go forward with your PR!

I rebased it on current master and added CI tests for compiling and running on windows in [this PR](https://github.com/weaviate/weaviate/pull/3295). Your commit is kept so you are getting credit for your work :)

Thanks again for this and would be great if you could have a quick look at my changes. One thing I couldn't figure out was support for text2vec-contextionary on GHA - you cannot run linux containers on the windows runners and we currently do not build text2vec-contextionary for windows.

**Comment by ahmedalhulaibi** [comment]
Thanks for seeing it through @dirkkul! I'm glad I could help!

I actually did start looking at the text2vec-contextionary as that was the next blocker I faced. I haven't quite had enough time as of late to see it through, there's some windows system libraries that need to be conditionally pulled in. Can't remember off the top of my head.

**Comment by dirkkul** [comment]
Would be great if you could have a look at text2vec-contextionary :)

None of us has that much windows experience (and hardware). With text2vec-contextionary we could run our full acceptance test suite on windows and could ensure that everything works correctly in the future

**Pull request closed without merging**
