### PR TITLE
Add endpoint for checking if tenant exists

### PR DESCRIPTION
**Pull request by litlig**
### What's being changed:
https://github.com/weaviate/weaviate/issues/3472

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by litlig** [comment]
I  agree with the CLA

**Comment by tsmith023** [comment]
Hi @litlig, thanks for the PR for this feature! The [CI fails](https://github.com/weaviate/weaviate/actions/runs/7810028088/job/21470197037?pr=4155) because you need to run the auto-generation code to generate the Go structs from the OpenAPI swagger config, cheers!

**Comment by litlig** [comment]
hey @tsmith023, thanks for taking a look! I did run the gen-code-from-swagger.sh to autogen swagger code. The CI error seems to be complaining about `deprecations/data.go`, which got formatted by swagger gen. I reverted change to that file.

**Comment by tsmith023** [comment]
Hi @litlig, thanks for tidying up this PR and getting in such a good shape! I will give it a review in the coming days when I get the chance 😁

**Review by parkerduckworth — CHANGES_REQUESTED** [review]
Thanks for the contribution! Can you please add some tests? Probably just an acceptance (end2end) test would suffice. Check the existing [multi-tenancy tests](https://github.com/weaviate/weaviate/tree/master/test/acceptance/multi_tenancy) for reference

**Comment by litlig** [comment]
> Thanks for the contribution! Can you please add some tests? Probably just an acceptance (end2end) test would suffice. Check the existing [multi-tenancy tests](https://github.com/weaviate/weaviate/tree/master/test/acceptance/multi_tenancy) for reference

Thanks for the pointer! Tests added.

**Comment by parkerduckworth** [comment]
Very nice @litlig everything looks in order. Will have this merged in shortly

**Review by parkerduckworth — APPROVED** [review]

**Pull request merged**
