### PR TITLE
Update: Auto-gen description with time stamp

### LINKED ISSUE #2620: FR: Extend auto schema descriptions with human-readable timestamp
When a class (or property) is auto-generated through auto schema they are filled with a very simple description along the lines of `"auto-generated property"`. We could extend this description with a human-readable timestamp such as `"This property was generated by Weaviate's auto-schema feature on 2023-02-13 10:42:00"` or similar. This applies to any description added by auto-schema.

### PR DESCRIPTION
**Pull request by srini047**
### What's being changed:
Updated the description to more customized one.

### Fixes
#2620 

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [x] Performance tests have been run or not necessary.

### CODE REVIEW

**Comment by etiennedi** [comment]
Hi, I've enabled CI. I think the code does not currently compile, you can expand the individual CI steps to see how/why they're failing.

**Comment by srini047** [comment]
Thanks much 😊
Let me fix it

**Comment by srini047** [comment]
@etiennedi I have made the changes mind re-rerunning the workflow

**Comment by etiennedi** [comment]
Thanks! It seems our CLA bot is currently broken, so let me post the [CLA](https://weaviate.io/service/contributor-license-agreement) manually. 

If you agree, let me know, and then we can merge.

**Comment by srini047** [comment]
> Thanks! It seems our CLA bot is currently broken, so let me post the [CLA](https://weaviate.io/service/contributor-license-agreement) manually. 
> 
> If you agree, let me know, and then we can merge.

Agreed ✍️

**Comment by srini047** [comment]
> To avoid any confusion in the future about your contribution to Weaviate, we work with a [Contributor License Agreement](https://www.semi.technology/playbooks/misc/contributor-license-agreement.html). If you agree, you can simply add a comment to this PR that you agree with the CLA so that we can merge.
> 
> beep boop - the SeMI bot 👋🤖
> 
> PS:
> Are you already a member of the [Weaviate Slack channel?](https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw)

Agree with CLA

**Comment by dirkkul** [comment]
Thank you for the contribution!

**Comment by srini047** [comment]
> Thank you for the contribution!

Welcome. Would love to contribute more.

**Pull request merged**
